server:
  port: ${EUREKA_SERVER_PORT:8761}  # Dac? variabila EUREKA_SERVER_PORT nu este setat?, va folosi 8761 ca valoare implicit?

eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: eureka-server
